autoload -Uz compinit && compinit

source <(antibody init)

antibody bundle robbyrussell/oh-my-zsh path:plugins/extract
antibody bundle robbyrussell/oh-my-zsh path:plugins/sudo
antibody bundle robbyrussell/oh-my-zsh path:plugins/z

antibody bundle edieguez/zsh-config path:themes/aya.zsh-theme
